# Generated by Django 4.2.2 on 2023-06-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.IntegerField()),
                ('campo3', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbTabla1',
            },
        ),
        migrations.CreateModel(
            name='Tabla2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=50)),
                ('campo2', models.TextField()),
                ('campo3', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbTabla2',
            },
        ),
        migrations.CreateModel(
            name='Tabla3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=200)),
                ('campo2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('campo3', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbTabla3',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'tblUsuario',
            },
        ),
    ]
